
version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
  web:
    build: .
    command: /bin/sh -c "/entrypoint.sh"
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"

  tailwind:
    image: node:20.11.1-slim
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static

volumes:
  static_volume:
  postgres_data:
