global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tensorflow_serving'
    scrape_interval: 5s
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ['tensorflow_serving:8501']